name: Java Testing

on:
  Push:
    Branches: ["main"]
  pull_request:
    Branches: ["main"]

jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: Set up JDK 11 for x64
     uses: actions/setup-java@v3
     with:
       java-version: '11'
       distribution: 'temurin'
       architecture: x64
  
   - name: Run the Ant jar target
     run: ant -noinput -buildfile build-ci.xml jar
   - uses: actions/upload-artifact@v3
     with:
       name: Package
       path: build/jar  
